/**
 * GENERATED by tools/export_gfx_metrics.py — do not edit by hand.
 *
 * Per-font metrics for the firmware's embedded Adafruit GFX bitmap fonts,
 * so the editor can predict truncation and alignment EXACTLY as the panel
 * will render them. Indexed by `region::FontId` (src/region.h); those
 * numeric values are on the wire, so this array may be appended to but
 * never reordered.
 *
 * `advances[i]` is the pixel advance of ASCII character (0x20 + i).
 * Glyph SHAPES in the editor preview are still browser-rendered and
 * therefore approximate; only these metrics are exact.
 */

export const FIRST_PRINTABLE = 0x20;
export const LAST_PRINTABLE = 0x7e;
export const ADVANCE_TABLE_LEN = 95;

export interface GfxFontMetrics {
  /** Human label for the font picker. */
  label: string;
  /** Tallest extent above the baseline, px. */
  ascent: number;
  /** Deepest extent below the baseline, px. */
  descent: number;
  /** Font line advance, px. */
  lineHeight: number;
  /** ADVANCE_TABLE_LEN entries, indexed by (charCode - FIRST_PRINTABLE). */
  advances: readonly number[];
}

export const GFX_FONTS: readonly GfxFontMetrics[] = [
  {
    label: "Sans 9",
    ascent: 13,
    descent: 5,
    lineHeight: 22,
    advances: [5, 6, 6, 10, 10, 16, 12, 4, 6, 6, 7, 11, 5, 6, 5, 5, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 5, 5, 11, 11, 11, 10, 18, 12, 12, 13, 13, 11, 11, 14, 13, 5, 10, 12, 10, 15, 13, 14, 12, 14, 13, 12, 11, 13, 12, 17, 12, 12, 11, 5, 5, 5, 8, 10, 5, 10, 10, 9, 10, 10, 5, 10, 10, 4, 4, 9, 4, 15, 10, 10, 10, 10, 6, 9, 5, 10, 9, 13, 9, 9, 9, 6, 4, 6, 9],
  },
  {
    label: "Sans 12",
    ascent: 17,
    descent: 6,
    lineHeight: 29,
    advances: [6, 8, 8, 13, 13, 21, 16, 5, 8, 8, 9, 14, 7, 8, 6, 7, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 6, 6, 14, 14, 14, 13, 24, 16, 16, 17, 17, 15, 14, 18, 17, 7, 13, 16, 14, 20, 18, 19, 16, 19, 17, 16, 15, 17, 15, 22, 16, 16, 15, 7, 7, 7, 11, 13, 6, 13, 13, 12, 13, 13, 7, 13, 13, 5, 6, 12, 5, 19, 13, 13, 13, 13, 8, 12, 7, 13, 12, 17, 11, 11, 12, 8, 6, 8, 12],
  },
  {
    label: "Sans Bold 12",
    ascent: 17,
    descent: 6,
    lineHeight: 29,
    advances: [7, 8, 11, 13, 13, 21, 17, 6, 8, 8, 9, 14, 6, 8, 6, 7, 13, 14, 13, 13, 13, 13, 13, 13, 13, 13, 6, 6, 14, 14, 14, 15, 23, 17, 17, 17, 17, 16, 15, 18, 18, 7, 14, 17, 15, 21, 18, 19, 16, 19, 17, 16, 15, 18, 16, 23, 16, 15, 15, 8, 7, 8, 14, 13, 6, 14, 15, 13, 15, 14, 8, 15, 14, 7, 7, 14, 6, 21, 15, 15, 15, 15, 9, 13, 8, 15, 13, 19, 13, 13, 12, 9, 7, 9, 12],
  },
  {
    label: "Sans Bold 18",
    ascent: 25,
    descent: 8,
    lineHeight: 42,
    advances: [10, 12, 17, 19, 19, 31, 25, 9, 12, 12, 14, 20, 9, 12, 9, 10, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 9, 9, 20, 20, 20, 21, 34, 24, 25, 25, 25, 23, 22, 27, 26, 11, 20, 25, 22, 30, 26, 27, 24, 27, 25, 24, 23, 26, 23, 34, 24, 22, 21, 12, 10, 12, 20, 19, 9, 20, 22, 20, 22, 20, 12, 21, 21, 10, 10, 20, 9, 31, 21, 21, 22, 22, 14, 19, 12, 21, 19, 27, 19, 19, 18, 14, 10, 14, 18],
  },
  {
    label: "Sans Bold 24",
    ascent: 35,
    descent: 12,
    lineHeight: 56,
    advances: [13, 16, 22, 26, 26, 42, 34, 12, 16, 16, 18, 27, 12, 16, 12, 13, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 12, 12, 27, 27, 27, 29, 46, 33, 33, 34, 34, 31, 30, 36, 35, 15, 27, 34, 29, 41, 35, 37, 32, 37, 34, 32, 30, 35, 31, 45, 32, 30, 29, 16, 13, 16, 27, 26, 12, 27, 29, 26, 29, 27, 16, 29, 28, 13, 13, 27, 13, 42, 29, 29, 29, 29, 18, 26, 16, 29, 25, 37, 26, 26, 24, 18, 13, 18, 23],
  },
  {
    label: "Sans Bold 24 ×2 (hero)",
    ascent: 70,
    descent: 24,
    lineHeight: 112,
    advances: [26, 32, 44, 52, 52, 84, 68, 24, 32, 32, 36, 54, 24, 32, 24, 26, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 24, 24, 54, 54, 54, 58, 92, 66, 66, 68, 68, 62, 60, 72, 70, 30, 54, 68, 58, 82, 70, 74, 64, 74, 68, 64, 60, 70, 62, 90, 64, 60, 58, 32, 26, 32, 54, 52, 24, 54, 58, 52, 58, 54, 32, 58, 56, 26, 26, 54, 26, 84, 58, 58, 58, 58, 36, 52, 32, 58, 50, 74, 52, 52, 48, 36, 26, 36, 46],
  },
  {
    label: "Mono Bold 18",
    ascent: 23,
    descent: 8,
    lineHeight: 35,
    advances: [21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 22, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21],
  },
  {
    label: "Mono Bold 24",
    ascent: 32,
    descent: 10,
    lineHeight: 47,
    advances: [28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28],
  },
] as const;
