/**
 * Wire-format spec module — JS/TS mirror of tools/frame_format.py.
 *
 * Authoritative reference: docs/protocol.md §1.
 * Equivalence with the Python module is enforced by frameFormat.test.ts
 * comparing packFrame1bppMsb output to a committed binary fixture
 * generated by tools/generate_oracle_fixture.py.
 *
 * Any change here must update tools/frame_format.py, regenerate the
 * fixture, and bump the protocol version in docs/protocol.md.
 */

export const WIDTH = 800;
export const HEIGHT = 480;
export const FRAME_BYTES = (WIDTH / 8) * HEIGHT; // 48000

/**
 * Pack a row-major sequence of {@link WIDTH} × {@link HEIGHT} pixels into
 * 1bpp MSB-first bytes. Truthy = ink (bit set), falsy = paper (bit clear).
 * Within each byte, the leftmost pixel of the group of 8 occupies bit 7.
 *
 * Throws if the input length is wrong; this is a programmer error, not a
 * runtime condition we want to swallow.
 */
export function packFrame1bppMsb(
  pixels: ArrayLike<number>,
): Uint8Array {
  if (pixels.length !== WIDTH * HEIGHT) {
    throw new Error(
      `expected ${WIDTH * HEIGHT} pixels, got ${pixels.length}`,
    );
  }
  const out = new Uint8Array(FRAME_BYTES);
  const bytesPerRow = WIDTH / 8;
  for (let y = 0; y < HEIGHT; y++) {
    const rowBase = y * WIDTH;
    const byteBase = y * bytesPerRow;
    for (let bx = 0; bx < bytesPerRow; bx++) {
      let b = 0;
      const pxBase = rowBase + bx * 8;
      for (let bit = 0; bit < 8; bit++) {
        if (pixels[pxBase + bit]) b |= 1 << (7 - bit);
      }
      out[byteBase + bx] = b;
    }
  }
  return out;
}

/**
 * Inverse of {@link packFrame1bppMsb}. Returns a Uint8Array of length
 * {@link WIDTH} × {@link HEIGHT} containing 0 or 1 per pixel.
 */
export function unpackFrame1bppMsb(data: ArrayLike<number>): Uint8Array {
  if (data.length !== FRAME_BYTES) {
    throw new Error(`expected ${FRAME_BYTES} bytes, got ${data.length}`);
  }
  const out = new Uint8Array(WIDTH * HEIGHT);
  const bytesPerRow = WIDTH / 8;
  for (let y = 0; y < HEIGHT; y++) {
    const rowBase = y * WIDTH;
    const byteBase = y * bytesPerRow;
    for (let bx = 0; bx < bytesPerRow; bx++) {
      const b = data[byteBase + bx];
      const pxBase = rowBase + bx * 8;
      for (let bit = 0; bit < 8; bit++) {
        out[pxBase + bit] = (b >> (7 - bit)) & 1;
      }
    }
  }
  return out;
}
