import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { describe, expect, it } from "vitest";

import {
  FRAME_BYTES,
  HEIGHT,
  WIDTH,
  packFrame1bppMsb,
  unpackFrame1bppMsb,
} from "./frameFormat";

const __dirname = dirname(fileURLToPath(import.meta.url));

describe("frameFormat constants", () => {
  it("matches the protocol-locked dimensions", () => {
    expect(WIDTH).toBe(800);
    expect(HEIGHT).toBe(480);
    expect(FRAME_BYTES).toBe(48000);
    expect(FRAME_BYTES).toBe((WIDTH / 8) * HEIGHT);
  });
});

describe("packFrame1bppMsb", () => {
  it("packs an all-white frame to 48000 zero bytes", () => {
    const pixels = new Uint8Array(WIDTH * HEIGHT);
    const out = packFrame1bppMsb(pixels);
    expect(out.length).toBe(FRAME_BYTES);
    expect(out.every((b) => b === 0)).toBe(true);
  });

  it("packs an all-black frame to 48000 0xFF bytes", () => {
    const pixels = new Uint8Array(WIDTH * HEIGHT).fill(1);
    const out = packFrame1bppMsb(pixels);
    expect(out.length).toBe(FRAME_BYTES);
    expect(out.every((b) => b === 0xff)).toBe(true);
  });

  it("places (x=0, y=0) in the MSB of byte 0", () => {
    const pixels = new Uint8Array(WIDTH * HEIGHT);
    pixels[0] = 1;
    const out = packFrame1bppMsb(pixels);
    expect(out[0]).toBe(0x80);
    for (let i = 1; i < FRAME_BYTES; i++) expect(out[i]).toBe(0);
  });

  it("places (x=7, y=0) in the LSB of byte 0", () => {
    const pixels = new Uint8Array(WIDTH * HEIGHT);
    pixels[7] = 1;
    const out = packFrame1bppMsb(pixels);
    expect(out[0]).toBe(0x01);
  });

  it("places (x=8, y=0) in the MSB of byte 1", () => {
    const pixels = new Uint8Array(WIDTH * HEIGHT);
    pixels[8] = 1;
    const out = packFrame1bppMsb(pixels);
    expect(out[0]).toBe(0x00);
    expect(out[1]).toBe(0x80);
  });

  it("places (x=0, y=1) at the start of byte 100 (row stride)", () => {
    const pixels = new Uint8Array(WIDTH * HEIGHT);
    pixels[WIDTH] = 1;
    const out = packFrame1bppMsb(pixels);
    expect(out[100]).toBe(0x80);
    for (let i = 0; i < 100; i++) expect(out[i]).toBe(0);
  });

  it("treats any non-zero byte as ink", () => {
    const pixels = new Uint8Array(WIDTH * HEIGHT);
    pixels[0] = 1;
    pixels[1] = 255;
    pixels[2] = 7;
    const out = packFrame1bppMsb(pixels);
    expect(out[0]).toBe(0xe0); // 0b11100000
  });

  it("rejects pixel buffers of the wrong length", () => {
    expect(() => packFrame1bppMsb(new Uint8Array(WIDTH * HEIGHT - 1))).toThrow();
    expect(() => packFrame1bppMsb(new Uint8Array(WIDTH * HEIGHT + 1))).toThrow();
  });
});

describe("unpackFrame1bppMsb", () => {
  it("inverts packFrame1bppMsb on a deterministic checkerboard", () => {
    const pixels = new Uint8Array(WIDTH * HEIGHT);
    for (let y = 0; y < HEIGHT; y++) {
      for (let x = 0; x < WIDTH; x++) {
        pixels[y * WIDTH + x] = (x + y) % 2 === 0 ? 1 : 0;
      }
    }
    const packed = packFrame1bppMsb(pixels);
    const round = unpackFrame1bppMsb(packed);
    expect(round.length).toBe(WIDTH * HEIGHT);
    // Bulk equality — per-pixel expect() takes seconds on 384k pixels.
    let firstDiff = -1;
    for (let i = 0; i < pixels.length; i++) {
      if (round[i] !== pixels[i]) {
        firstDiff = i;
        break;
      }
    }
    expect(firstDiff).toBe(-1);
  });

  it("rejects byte buffers of the wrong length", () => {
    expect(() => unpackFrame1bppMsb(new Uint8Array(FRAME_BYTES - 1))).toThrow();
    expect(() => unpackFrame1bppMsb(new Uint8Array(FRAME_BYTES + 1))).toThrow();
  });
});

// ---------------------------------------------------------------------------
// Cross-language oracle. The fixture at __fixtures__/oracle_frame.bin is
// generated by tools/generate_oracle_fixture.py, which uses the Python
// frame_format module. If this test fails, either:
//   - the JS encoder drifted from the Python one, OR
//   - the fixture wasn't regenerated after a deliberate format change.
// Either way, fix it before merging — this is the contract enforcement.
// ---------------------------------------------------------------------------
describe("cross-language oracle", () => {
  it("matches the Python-generated fixture byte-for-byte", () => {
    const fixturePath = resolve(__dirname, "__fixtures__/oracle_frame.bin");
    const expected = readFileSync(fixturePath);
    expect(expected.length).toBe(FRAME_BYTES);

    const pixels = new Uint8Array(WIDTH * HEIGHT);
    for (let y = 0; y < HEIGHT; y++) {
      for (let x = 0; x < WIDTH; x++) {
        pixels[y * WIDTH + x] = (x * 31 + y * 7) % 5 === 0 ? 1 : 0;
      }
    }
    const actual = packFrame1bppMsb(pixels);
    expect(actual.length).toBe(expected.length);

    // Find first divergence to make a failure message actually useful.
    let firstMismatch = -1;
    for (let i = 0; i < FRAME_BYTES; i++) {
      if (actual[i] !== expected[i]) {
        firstMismatch = i;
        break;
      }
    }
    expect(firstMismatch).toBe(-1);
  });
});
