import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { describe, expect, it } from "vitest";

import { FRAME_BYTES, HEIGHT, WIDTH, unpackFrame1bppMsb } from "./frameFormat";
import { packFrame } from "./packFrame";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ---------------------------------------------------------------------------
// Phase 3 canvas-glue oracle. Proves the full RGBA → luminance → threshold →
// 1bpp MSB-first pipeline produces canonical bytes when fed canonical pixels.
//
// Source of truth: clapper_hero.bin (48000 bytes), generated by
// `python tools/dump_slide.py --slide clapper_hero`. clapper_hero is a
// threshold-only slide (no greys), so canvas-style RGBA reconstruction round-
// trips exactly through packFrame.
//
// Why we don't re-render the slate in canvas: HTML5 canvas and PIL won't
// byte-agree on text or polygon rasterisation; a "render same image, byte-
// match Python" test would measure cross-rasterizer determinism, not the
// packer. Unpack → resynthesise RGBA → repack tests the actual claim.
// ---------------------------------------------------------------------------
describe("canvas glue oracle (clapper_hero)", () => {
  it("repacking the unpacked fixture as RGBA matches the original bytes", () => {
    const fixturePath = resolve(
      __dirname,
      "__fixtures__/clapper_hero.bin",
    );
    const expected = readFileSync(fixturePath);
    expect(expected.length).toBe(FRAME_BYTES);

    const pixels = unpackFrame1bppMsb(expected);
    expect(pixels.length).toBe(WIDTH * HEIGHT);

    // Synthesise the RGBA an HTML canvas would yield: ink → opaque black,
    // paper → opaque white. Alpha 255 throughout.
    const data = new Uint8ClampedArray(WIDTH * HEIGHT * 4);
    for (let i = 0; i < pixels.length; i++) {
      const v = pixels[i] ? 0 : 255;
      const o = i * 4;
      data[o + 0] = v;
      data[o + 1] = v;
      data[o + 2] = v;
      data[o + 3] = 255;
    }
    const imageData = { data, width: WIDTH, height: HEIGHT };

    const actual = packFrame(imageData);
    expect(actual.length).toBe(expected.length);

    let firstMismatch = -1;
    for (let i = 0; i < FRAME_BYTES; i++) {
      if (actual[i] !== expected[i]) {
        firstMismatch = i;
        break;
      }
    }
    expect(firstMismatch).toBe(-1);
  });
});
